main: com.mycompany.translatemanager.TranslateManager
name: TranslateManager
version: ${project.version}
description: ${project.description}
author: Kumaisu
database: true
api-version: 1.14
commands:
    trans:
        description: Translate Command
        aliases: tr
        permission: TransMan.Translate
        permission-message: You do not have permission.
        default: op
        usage: |
            /<command> [Language] [Message]
            /<command> reload
